"""
PR Comment Poster
==================
Maps Finding objects → GitHub PR review with inline line comments.

GitHub's PR review API lets you post:
1. A review body (markdown summary at the bottom of the PR)
2. Inline comments on specific lines of the diff

This module translates our structured Finding objects into those formats.
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from app.schemas import Finding, ReviewMetadata, Severity

if TYPE_CHECKING:
    from app.github.client import GitHubClient

logger = logging.getLogger(__name__)

# Severity → emoji mapping for the PR comment
_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}

_CATEGORY_LABEL = {
    "security": "🔒 Security",
    "style": "🎨 Style",
    "test_coverage": "🧪 Test Coverage",
    "logic": "🐛 Logic/Bug",
}


def build_review_body(
    findings: list[Finding],
    metadata: ReviewMetadata,
    pr_title: str,
) -> str:
    """
    Build the Markdown summary comment to post on the PR.

    This is the main review body that appears at the bottom of the PR.
    Inline comments are posted separately.
    """
    if not findings:
        return _build_clean_review(metadata, pr_title)

    # Group findings by severity
    by_severity: dict[str, list[Finding]] = {}
    for f in findings:
        by_severity.setdefault(f.severity.value, []).append(f)

    # Stats
    critical_count = len(by_severity.get("critical", []))
    high_count = len(by_severity.get("high", []))
    medium_count = len(by_severity.get("medium", []))

    lines = [
        "## 🤖 CodeSentinel Review",
        "",
        f"> **PR:** {pr_title}",
        f"> **Findings:** {len(findings)} total "
        f"({critical_count} critical, {high_count} high, {medium_count} medium)",
        f"> **Agents:** {', '.join(metadata.agents_invoked)}",
        f"> **Cost:** ~${metadata.estimated_cost_usd:.4f} | "
        f"**Latency:** {metadata.total_latency_ms:.0f}ms",
        "",
    ]

    if metadata.agents_degraded:
        lines += [
            f"> ⚠️ **Degraded agents (partial results):** {', '.join(metadata.agents_degraded)}",
            "",
        ]

    # Summary table
    lines += [
        "### Summary",
        "",
        "| Severity | Count | Category |",
        "|----------|-------|----------|",
    ]
    for severity in ["critical", "high", "medium", "low", "info"]:
        group = by_severity.get(severity, [])
        if group:
            emoji = _SEVERITY_EMOJI[Severity(severity)]
            categories = ", ".join(
                sorted({_CATEGORY_LABEL.get(f.category.value, f.category.value) for f in group})
            )
            lines.append(f"| {emoji} {severity.capitalize()} | {len(group)} | {categories} |")

    lines += ["", "---", "", "### Findings", ""]

    # Findings list (only critical/high/medium inline in summary)
    shown = [f for f in findings if f.severity in {Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM}]
    if not shown:
        shown = findings[:10]

    for i, finding in enumerate(shown, 1):
        emoji = _SEVERITY_EMOJI[finding.severity]
        category = _CATEGORY_LABEL.get(finding.category.value, finding.category.value)
        lines += [
            f"#### {i}. {emoji} `{finding.file}:{finding.line}` — {category}",
            "",
            f"**{finding.message}**",
            "",
            f"*Confidence: {finding.confidence:.0%}*"
            + (f" | Rule: `{finding.rule_id}`" if finding.rule_id else ""),
            "",
        ]
        if finding.suggested_fix:
            lines += [
                "<details>",
                "<summary>💡 Suggested Fix</summary>",
                "",
                "```python",
                finding.suggested_fix,
                "```",
                "</details>",
                "",
            ]

    if len(findings) > len(shown):
        lines += [
            f"*...and {len(findings) - len(shown)} more findings (see inline comments)*",
            "",
        ]

    lines += [
        "---",
        "",
        "<sub>Generated by [CodeSentinel](https://github.com/your/codesentinel) · "
        f"Request ID: `{metadata.request_id}`</sub>",
    ]

    return "\n".join(lines)


def _build_clean_review(metadata: ReviewMetadata, pr_title: str) -> str:
    """Review body when no issues are found."""
    return (
        "## 🤖 CodeSentinel Review\n\n"
        f"> **PR:** {pr_title}\n\n"
        "✅ **No issues found.** This PR looks clean across all review dimensions.\n\n"
        f"Agents run: {', '.join(metadata.agents_invoked)}\n\n"
        f"<sub>Generated by CodeSentinel · Request ID: `{metadata.request_id}`</sub>"
    )


def build_inline_comments(findings: list[Finding]) -> list[dict]:
    """
    Convert Finding objects into GitHub review inline comment dicts.

    Returns a list of dicts:
        {"path": str, "line": int, "body": str}

    GitHub requires that the line must be in the PR diff. We post all findings
    and let the client skip ones that aren't (the client handles GithubException).
    """
    comments = []
    for finding in findings:
        emoji = _SEVERITY_EMOJI[finding.severity]
        category = _CATEGORY_LABEL.get(finding.category.value, finding.category.value)

        body_lines = [
            f"**{emoji} {finding.severity.value.capitalize()} — {category}**",
            "",
            finding.message,
        ]

        if finding.suggested_fix:
            body_lines += [
                "",
                "<details>",
                "<summary>💡 Suggested Fix</summary>",
                "",
                "```python",
                finding.suggested_fix,
                "```",
                "</details>",
            ]

        if finding.rule_id:
            body_lines += ["", f"*Rule: `{finding.rule_id}`*"]

        body_lines += [
            "",
            f"*Confidence: {finding.confidence:.0%} | "
            f"Tool: {finding.tool or 'llm'} | "
            f"CodeSentinel*",
        ]

        comments.append(
            {
                "path": finding.file,
                "line": finding.line,
                "body": "\n".join(body_lines),
            }
        )

    return comments


async def post_review(
    github_client: "GitHubClient",
    repo_full_name: str,
    pr_number: int,
    pr_title: str,
    commit_sha: str,
    findings: list[Finding],
    metadata: ReviewMetadata,
) -> None:
    """
    Post the complete PR review: summary body + inline annotations.

    This is the final step of the pipeline.
    """
    review_body = build_review_body(findings, metadata, pr_title)
    inline_comments = build_inline_comments(findings)

    logger.info(
        "Posting review: %d findings, %d inline comments on %s#%d",
        len(findings),
        len(inline_comments),
        repo_full_name,
        pr_number,
    )

    github_client.post_review(
        repo_full_name=repo_full_name,
        pr_number=pr_number,
        body=review_body,
        inline_comments=inline_comments,
        commit_sha=commit_sha,
        event="COMMENT",
    )
